### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by indutny** [indutny/gyp.js#3]
There are lots of `TODO: windows` (and similar) through out this repo (like [here][0]).

Mainly, Windows has different command-line options for compilers, so things like:

- [x] defines
- [x] includes
- [x] linking
- [x] compiling
- [x] creating archives
- [x] creating dlls
- [ ] extensive testing!

Needs to be done. Possibly more. Minimal goal at this point is to be able to build Node.js.

[0]: https://github.com/indutny/gyp.js/blob/master/lib/gyp/generator/ninja/index.js

**Comment by indutny** [comment]
I have pushed some code, not sure how much of it works, though, as I don't have a Windows machine cc @nodejs/build

**Comment by indutny** [comment]
After some investigation I'm inclined to say that it would be easier to just use clang for Windows builds.

**Comment by indutny** [comment]
Added `extensive testing`, and closed the rest.

**Comment by ccoenen** [comment]
How can I help testing? Is a clone and a nice run of `npm test` good enough? If not: are there instructions You'd like me to run additionally?

**Comment by indutny** [comment]
@ccoenen good question! I have no answer for this right now.

The ideal solution would be to take node.js addons that are known to build and run fine on Windows, build them with `gyp.js` and verify that their tests pass. Perhaps, something along this lines.

cc @Fishrock123 as it appears to be very similar to the smoke testing that we do in @nodejs

**Comment by ccoenen** [comment]
My machine is currently on node 5.3.0, I'll upgrade and retry. Currently the tests fail like this:

```
C:\Users\user\workspace\gyp.js (master) (gyp.js@1.1.0)
λ npm test

> gyp.js@1.1.0 test C:\Users\user\workspace\gyp.js
> mocha --reporter=spec test/*-test.js && npm run lint

C:\Users\user\workspace\gyp.js\lib\gyp.js:56
function load(buildFiles, format, defaultVariables = {}, includes = [],
                                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\workspace\gyp.js\lib\gyp\generator\ninja\writer.js:3:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\user\workspace\gyp.js\test\generator-ninja-writer-test.js:6:21)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\Users\user\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\user\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\user\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
npm ERR! Test failed.  See above for more details.
```

**Comment by ccoenen** [comment]
disregard my posting (i deleted just now) I am a moron.

**Comment by ccoenen** [comment]
The Mocha Suite runs fine!

```
C:\Users\amenthes\workspace\gyp.js (master) (gyp.js@1.1.0)
λ npm test

> gyp.js@1.1.0 test C:\Users\amenthes\workspace\gyp.js
> mocha --reporter=spec test/*-test.js && npm run lint



  gyp.generator.ninja.writer
    escape
      √ should not escape empty string
      √ should not escape regular string
      √ should escape ` `
      √ should escape `$` symbols
      √ should escape `:` symbols
      √ should escape ` `, `$` and `:` symbols

  gyp.platform.win
    adjustLibraries
      √ should be empty
      √ should remove prefix `-l`
      √ should append suffix `.lib`
      √ should remove prefix `-l` and append suffix `.lib`
      √ should preserve quotes
    targetFlags
      √ disable specific warnings
      √ compiler
      √ librarian
      √ linker
    escapeDefine
      √ should escape %
      √ should escape "
      √ should escape \"

  gyp.py.Base
    √ should return proper pos

  gyp.py.compileCondition
    √ should eval number
    √ should eval string
    √ should eval identifier
    √ should eval object
    √ should eval array
    unary
      √ should eval `.split()`
    binary
      √ should eval ==
      √ should eval !=
      √ should eval >=
      √ should eval <=
      √ should eval >
      √ should eval <
      √ should eval "in"
      √ should eval "not in"
      √ should eval "and"
      √ should eval "or"

  gyp.py.parseJSON
    number
      √ should parse integer
      √ should parse negative integer
      √ should parse float
      √ should validate number
      √ should validate number
    string
      √ should parse single-quote string
      √ should parse double-quote string
      √ should parse escape sequences in a string
      √ should parse double single-quote string
      √ should parse escaped windows newline in string
      √ should validate string
    array
      √ should parse empty array
      √ should parse element array
      √ should parse element+comma array
      √ should parse multi-element array
    object
      √ should parse empty object
      √ should parse single property object
      √ should parse single property + comma object
      √ should parse multi-property object
    comments
      √ should ignore comments
      √ should ignore window-style comments

  gyp.py.parseCondition
    √ should parse number
    √ should parse string
    √ should parse identifier
    √ should parse parens
    √ should parse tuple
    unary
      √ should parse single `not`
      √ should parse `.split()`
      √ should parse double `not`
      √ should parse `not` in expression
    binary
      √ should parse `and`
      √ should parse `>=`
      √ should parse nested

  gyp.shlex
    √ should split words
    √ should coalesce parts in single quotes
    √ should coalesce parts in double quotes
    √ should not escape `\` in single quotes
    √ should escape `\` in double quotes
    √ should escape `\"` in double quotes


  74 passing (83ms)
```

The lint command does not, for the lack of `make` on windows. But this shouldn't stop me to GYP ALL THE THINGS. :D

**Comment by indutny** [comment]
Haha! Thanks!

**Comment by ccoenen** [comment]
Turns out, I have no idea how to gyp anything. Is there a good starting point that I could teach myself? The README states that this is already able to build node.js itself. How would I go about doing that?

**Comment by indutny** [comment]
@ccoenen just pushed out 1e8614e3aa92006af59c133faed95ca34e477098. Should be possible to test it in a simpler way now!

Steps to run the new tests on Windows:

1. [download ninja][0]
2. open MSVS Developer console
3. set `NINJA` env variable to the full path to `ninja.exe`
4. run `npm test`

Didn't run it on Windows, but hopefully it will work!

[0]: https://github.com/ninja-build/ninja/releases

**Comment by indutny** [comment]
I'm inclined to say that it is working just fine on Windows. Going to close this issue and open a new one about the smoke tests.
